project:
  type: website
  output-dir: docs

website:
  title: "Val Eltagonde"
  navbar:
    background: secondary
    left:
      - text: Home
        href: index.qmd
      - href: competitions.qmd
        icon: bookmarks
        text: Competitions
      - href: projects.qmd
        text: Projects
        icon: suit-heart
      # - href: blog.qmd
      #   icon: pen
      #   text: Blog
      # - href: cv.qmd
      #   icon: person
      #   text: CV
  # sidebar:
    # - title: "Projects"
    #   style: "docked"
    #   collapse-level: 2
    #   contents:
    #   - projects.qmd
    #   - projects/pjdsc_2023/index.qmd
    #   - projects/pjdsc_2024/index.qmd
    #   - projects/synergy_2024/index.qmd

  page-navigation: true
        
format:
  html:
    theme: 
      - simplex
      - custom.scss

    toc: true
    page-layout: full



